### ISSUE TITLE
Proper instructions please

### ISSUE THREAD

**Issue by Naatan** [Pizzaface/Alexa-Chromecast-Skill-2.0#22]
This step in particular:

> Go to developer.amazon.com and create a Skill mapped to the Lambda function ARN, intentSchemas and sample utterances are in config/.

Could you please elaborate? I don't want to spend my evening backwards engineering the code to figure out how to use it. I appreciate the hard work, but without proper instructions this likely won't go very far.

**Comment by futureup** [comment]
Hi Naatan, I made a video tutorial showing how it works step by step. Please take a look on https://www.youtube.com/watch?v=xAt8HLUtFSs

**Comment by Naatan** [comment]
Very cool, thanks for sharing!

**Comment by khmyznikov** [comment]
@futureup Stuck on last step - SNS subscription. PendingConfirmation into portal. I'm need a real ip address from my isp or not?

**Comment by jinxo13** [comment]
The issue here is probably access to the port the local listener is running on.
The SNS subscription confirmation is sent back to <external IP>:<port>

When the local listener starts up (via ./start.sh/docker-start.sh) it will show the external IP and port it has used.
It relies on UPNP to allow port access. If UPNP is not available or disabled then you can specify a port and then setting up port forwarding.
e.g.
./start.sh -p 30000

If you are behind a VPN this may also cause issues, as the port is likely not accessible.
You can override the external IP to your non-VPN IP and see if that helps.
./start.sh -i 123.123.123.123 -p 30000
